### ISSUE TITLE
Five demo services

### ISSUE THREAD

**Issue by derega** [haltu/velmu-mpass-ansible#2]
We want to have five demo services on the Velmu desktop to showcase how MPASS works in real life. These five demo services will live on the same server as Velmu, but they will be completely independent services, with their own SAML SP:s.

Do this five (5) times:

* Create Apache vhost
* Shibboleth config for an SP, with its own entity id
* Register SP to MPASS
* Test that the SP config works

For now we don't yet know what kind of services we will be running here. Most probably Django, like Velmu, with minimal configuration to show one page. Or we will run mod_php. That's a separate issue.

**Comment by tkharju** [comment]
I have created five (5) new SP's that have been registered to MPASS idP and I was able to do MPASS-login against django test instance for each service. Closing this issue as done.
